export const tagsGroup: { name: string; tags: string[] }[] = [
  {
    name: "ClusterManagement",
    tags: [
      "Cluster",
      "ClusterSettings",
      "SnmpTransport",
      "SnmpTrapReceiver",
      "MigrateTransmitter",
    ],
  },
  {
    name: "MetroXClusterManagement",
    tags: ["Witness", "WitnessService", "Zone", "ZoneTopo"],
  },
  {
    name: "VmwareManagement",
    tags: ["VcenterAccount", "VsphereEsxiAccount"],
  },
  {
    name: "AlertManagement",
    tags: ["AlertNotifier", "Alert", "GlobalAlertRule", "AlertRule"],
  },
  {
    name: "VmManagement",
    tags: [
      "ElfImage",
      "VmDisk",
      "VmFolder",
      "VmNic",
      "VmPlacementGroup",
      "Vm",
      "VmSnapshot",
      "VmTemplate",
      "VmVolume",
      "VmVolumeSnapshot",
      "Ovf",
      "VmExportFile",
    ],
  },
  {
    name: "CloudTowerSetting",
    tags: [
      "Application",
      "ClusterImage",
      "ClusterUpgradeHistory",
      "Deploy",
      "GlobalSettings",
      "License",
      "SvtImage",
    ],
  },
  {
    name: "HardwareManagement",
    tags: [
      "BrickTopo",
      "RackTopo",
      "ClusterTopo",
      "DiscoveredHost",
      "Disk",
      "Host",
      "Ipmi",
      "NodeTopo",
      "PmemDimm",
      "UsbDevice",
      "GpuDevice",
    ],
  },
  {
    name: "StorageManagement",
    tags: [
      "ConsistencyGroup",
      "ConsistencyGroupSnapshot",
      "ElfDataStore",
      "ElfStoragePolicy",
      "IscsiConnection",
      "Iscsi",
      "IscsiLun",
      "IscsiLunSnapshot",
      "IscsiTarget",
      "NamespaceGroup",
      "NfsExport",
      "NfsInode",
      "NvmfNamespace",
      "NvmfNamespaceSnapshot",
      "NvmfSubsystem",
      "StoragePolicyConector",
    ],
  },
  {
    name: "SharedManagement",
    tags: ["ContentLibraryImage", "ContentLibraryVmTemplate"],
  },
  {
    name: "DatacneterAndOrgManagement",
    tags: ["Datacenter", "Organization"],
  },
  {
    name: "EntityFileterManagement",
    tags: ["EntityFilter", "VmEntityFilterResult"],
  },
  {
    name: "ErManagement",
    tags: ["EverouteCluster", "EverouteLicense", "EveroutePackage", "V2EverouteLicense"],
  },
  {
    name: "MonitorManagement",
    tags: ["Graph", "View", "Metrics"],
  },
  {
    name: "LabelManagement",
    tags: ["Label"],
  },
  {
    name: "LogManagement",
    tags: ["LogCollection", "LogServiceConfig"],
  },
  {
    name: "NetworkManagement",
    tags: ["Nic", "Vds", "Vlan"],
  },
  {
    name: "ReportManagement",
    tags: ["ReportTask", "ReportTemplate", "TableReporter"],
  },
  {
    name: "SnapshotManagement",
    tags: ["SnapshotGroup", "SnapshotPlan", "SnapshotPlanTask"],
  },
  {
    name: "AuditManagement",
    tags: ["SystemAuditLog", "UserAuditLog"],
  },
  {
    name: "TaskManagement",
    tags: ["Task", "UploadTask"],
  },
  {
    name: "UserManagement",
    tags: ["UserRoleNext", "User"],
  },
  {
    name: "BackupManagement",
    tags: [
      "BackupLicense",
      "BackupPackage",
      "BackupPlanExecution",
      "BackupPlan",
      "BackupRestoreExecution",
      "BackupRestorePoint",
      "BackupService",
      "BackupStoreRepository",
      "BackupTargetExecution",
    ],
  },
  {
    name: "CloudTowerApplicationManagement",
    tags: ["CloudTowerApplication", "CloudTowerApplicationPackage"],
  },
  {
    name: "DistributedFirewall",
    tags: ["IsolationPolicy", "SecurityPolicy", "SecurityGroup"],
  },
  {
    name: "VirtualPrivateCloudNetwork",
    tags: [
      "VirtualPrivateCloud",
      "VirtualPrivateCloudSubnet",
      "VirtualPrivateCloudRouteTable",
      "VirtualPrivateCloudSecurityGroup",
      "VirtualPrivateCloudSecurityPolicy",
      "VirtualPrivateCloudIsolationPolicy",
      "VirtualPrivateCloudNatGateway",
      "VirtualPrivateCloudRouterGateway",
      "VirtualPrivateCloudFloatingIp",
      "VirtualPrivateCloudClusterBinding",
      "VirtualPrivateCloudExternalSubnet",
    ],
  },
  {
    name: "Other",
    tags: ["ApiInfo"],
  },
];


export const APIVersionToSDKVersionMap = new Map([
  ['4.4.0', '2.18.0'],
  ['4.3.0', '2.17.0'],
  ['4.2.0', '2.16.0'],
  ['4.2.1', '2.16.0'],
  ['4.2.2', '2.16.0'],
  ['4.1.0', '2.15.1'],
  ['4.0.0', '2.14.0'],
  ['3.4.0', '2.13.1'],
  ['3.4.1', '2.13.1'],
  ['3.4.2', '2.13.1'],
  ['3.4.3', '2.13.1'],
  ['3.4.4', '2.13.1'],
  ['3.3.0', '2.12.0'],
  ['3.2.0', '2.11.0'],
  ['3.2.1', '2.11.0'],
  ['3.1.0', '2.10.0'],
  ['3.0.0', '2.9.0'],
  ['2.8.0', '2.8.0'],
  ['2.7.0', '2.7.0'],
  ['2.6.0', '2.6.0'],
  ['2.5.1', '2.5.0'],
  ['2.4.2', '2.4.0'],
  ['2.3.0', '2.3.0'],
  ['2.2.0', '2.2.0'],
  ['2.1.0', '2.1.0'],
])